### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#12]

**Comment by Edithosisike** [comment]
Done.

**Comment by Edithosisike** [comment]
Assigned task completed

**Comment by Edithosisike** [comment]
https://github.com/zuri-training/Proj_excel_Team-102/commit/46e5040c73b05d08259e4b35345e26331f699636

https://github.com/zuri-training/Proj_excel_Team-102/commits/frontend/login_page

link to the Login page created.
