### ISSUE TITLE
Sketches

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#22]
Link to the sketch

https://docs.google.com/document/d/1geaFUnZrwOcbsShBW3d561GXhLzWcI54WwcNxlIWluk/edit?usp=sharing)

**Comment by DEMIGODJADAK** [comment]
https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=658%3A4807
