### ISSUE TITLE
Hi-Fi Protype

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#23]

**Comment by A33sha** [comment]
We are done with the Hifi prototype
Desktop - https://www.figma.com/proto/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2%3A3&scaling=contain&starting-point-node-id=850%3A7321&show-proto-sidebar=1

Mobile- https://www.figma.com/proto/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2%3A3&scaling=contain&starting-point-node-id=1290%3A9583&show-proto-sidebar=1

Tablet- https://www.figma.com/proto/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2%3A3&scaling=contain&starting-point-node-id=1354%3A22155&show-proto-sidebar=1

Landing page mobile- https://www.figma.com/proto/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2%3A3&scaling=contain&starting-point-node-id=1821%3A28248&show-proto-sidebar=1
