### ISSUE TITLE
Compare cells from the processes down to the result

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#28]

**Comment by ugeeanya** [comment]
All screens for the compare files have been designed for the desktop, tablet and mobile.
First step: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1606%3A31333
Second step: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1632%3A29869
Third step: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1376%3A17248
