### ISSUE TITLE
Merge and Split cells from the processes down to the result

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#29]

**Comment by Ebele-Okafor** [comment]
I designed the Merge and Split Screens using Figma from the process down to the result.
-Low fi 
https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=385%3A3262

-High Fi 
https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1289%3A9705
