### ISSUE TITLE
Highlight duplicates, Search for keyword

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#30]

**Comment by kayuz97** [comment]
I have completed all the screens for this function
Highlight duplicates and return single file link-https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1344%3A13648
Highlight duplicates and return 2 files link-https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1344%3A13721
Search for keyword link-https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1417%3A30705
