### ISSUE TITLE
Dashboard Prototype

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#31]

**Comment by DEMIGODJADAK** [comment]
I worked on the Mid-fi wireframe of the dashboard

**Comment by DEMIGODJADAK** [comment]
Done with the dashboard HiFi

**Comment by DEMIGODJADAK** [comment]
HiFi prototype done and dusted

**Comment by DEMIGODJADAK** [comment]
https://www.figma.com/proto/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1199%3A7765&scaling=contain&page-id=2%3A3&starting-point-node-id=850%3A7321&show-proto-sidebar=1
