### ISSUE TITLE
Grid system and Spacer

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#34]

**Comment by ugeeanya** [comment]
The grid system and spacers are are complete.
Grids: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=90%3A5
Spacers: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=101%3A2
