### ISSUE TITLE
Outline and Filled icons

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#38]

**Comment by promiseokoh10** [comment]
[https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2%3A2](url)

**Comment by Ebele-Okafor** [comment]
Task Done
https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=100%3A29407
