### ISSUE TITLE
Journey map

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#40]

**Comment by designsbywonder** [comment]
I was assigned the user journey map alongside my partner and it has been completed

**Comment by DEMIGODJADAK** [comment]
> I was assigned the user journey map alongside my partner and it has been completed

Yea, was nice working with you @designsbywonder

**Comment by DEMIGODJADAK** [comment]
https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=410%3A900
