### ISSUE TITLE
Competitor analysis

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#41]

**Comment by Ebele-Okafor** [comment]
I worked with @Favour-Martins to create a competitor analysis of alternative software's using figjam
https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=9%3A706

**Comment by Favour-Martins** [comment]
I worked with @Ebele-Okafor to create a competitor analysis of our software using figjam.
