### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#42]

**Comment by kayuz97** [comment]
The userflow is done already here is a fig-jam link to the page-https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=9%3A554

**Comment by A33sha** [comment]
This has been completed and can be found here 
https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=136%3A665
