### ISSUE TITLE
Empathy Map/User story

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#43]

**Comment by ugeeanya** [comment]
I worked on the empathy map and user story during the user research. All tasks has been completed
Empathy map: https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=7%3A24
User story: https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=9%3A640
