### ISSUE TITLE
User Journey map, user Persona, User Flow, Information Architecture, Empathy Map, Pain Points, Priority Grid, Competitor Analysis

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#46]

**Comment by ugeeanya** [comment]
I did the pain points for the two user personas and it is complete.

**Comment by designsbywonder** [comment]
I was assigned the user journey map. And it has been completed

**Comment by DEMIGODJADAK** [comment]
I and @designsbywonder was assigned the User journey map. And it has been done
