### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by promiseokoh10** [zuri-training/Proj_excel_Team-102#5]
The styles that were done on the Style Guide includes the following:

- Grid System
- Desktop Grid System
- Color Gradient
- Text Styles
- Buttons
- Buttons with icon
- Input field text style
- Alerts
- Notifications
- Spacer
- Iconography
- Nav Bar and Footer
- Logo
- Selector
- Dropdown Menus

**Comment by Ebele-Okafor** [comment]
I worked on Iconography with variants (Outline and Filled icons).
https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=100%3A29407

**Comment by kayuz97** [comment]
I worked on the footer section (desktop view)https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=554%3A3851

**Comment by DEMIGODJADAK** [comment]
I worked on the Text Styles

**Comment by Favour-Martins** [comment]
I worked on desktop grid system and alerts.

**Comment by A33sha** [comment]
I worked on the Input system, Notificatons and Mobile Nav bar
