### ISSUE TITLE
Research Survey - Both Quantitative and Qualitative Interview

### ISSUE THREAD

**Issue by promiseokoh10** [zuri-training/Proj_excel_Team-102#6]
It should be carried out by @Ebele-Okafor and @morenikheji

**Comment by A33sha** [comment]
I created the survey for the Quantitative research as well as the screener survey for the Quantitatuve Research. These Questions were based and backed by our Problem statement and Research plan drafted by @Ebele-Okafor  and I.

The surveys can be found here
https://forms.gle/TXwj9at3St8oGyhJA
https://forms.gle/tjLQWtP2B1aWCYs37

**Comment by Ebele-Okafor** [comment]
I worked with @morenikheji on research survey and research plan. Task Done
https://docs.google.com/document/d/1Ubt80LYAmhLlCYm8FNXiISw22LKr4rnuALn264E_3Bc/edit?usp=sharing
