### ISSUE TITLE
File screen, Upload screen and File overview screen - Low-Fi

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#61]

**Comment by A33sha** [comment]
This has been completed and can be found here
Desktop View - https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=115%3A268
Tablet View - https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=175%3A730
Mobile View - https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=224%3A1805
