### ISSUE TITLE
File screen, Upload screen and File overview screen - High-Fi

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#62]

**Comment by A33sha** [comment]
This has been completed and can be found here
Desktop View - https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1309%3A10085
Tablet View -  https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1354%3A22155
Mobile View - https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1383%3A18463
