### ISSUE TITLE
Grids and Spacers

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#64]

**Comment by ugeeanya** [comment]
I have completed the grids and spacers as part of the style guides. 
This is the link to the grids: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=90%3A5
This is the link to the spacers: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=101%3A2
