### ISSUE TITLE
User pain points

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#65]

**Comment by ugeeanya** [comment]
I identified the users pain points for the user research 
https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=120%3A680
https://www.figma.com/file/lmMqrFQpKQ04e1wAXdNw3E/Figjam-for-Comparely?node-id=7%3A41
