### ISSUE TITLE
Compare files screen - High-Fi

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#67]

**Comment by ugeeanya** [comment]
I designed the high fidelity wireframes for the compare files screens. 
The link to the mobile screen: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1997%3A37799
The link to the tablet screen: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=2022%3A39712
The link to the desktop screen: https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1376%3A17248
