### ISSUE TITLE
Developers Schema

### ISSUE THREAD

**Issue by promiseokoh10** [zuri-training/Proj_excel_Team-102#8]

**Comment by Temitayo40** [comment]
we are meant to provide a well-structured framework for our database on Figma.

The link is provided below;
https://www.figma.com/file/JHMZA7HUAgm2kryvuJQMrM/Database-Schema

**Comment by promiseokoh10** [comment]
We have this already on the figma board. Just include it. Like input the figma link that contains the database schema.
