### ISSUE TITLE
Remove duplicate Page(return single file and return 2 files)

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#84]

**Comment by kayuz97** [comment]
I have designed all the screens for this function
return single file link- https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1344%3A13995
return 2 files link- https://www.figma.com/file/bxyWr1yL7bF1wrqU8gVYAk/Comparely?node-id=1417%3A29856
