### ISSUE TITLE
Developing features to ease comparison between excel files

### ISSUE THREAD

**Issue by Opeoluwa-A** [zuri-training/Proj_excel_Team-102#9]
Features to work on

- [x] Search and Highlight 
- [x] Search and replace
- [x] Highlight duplicates
- [ ] Merge files
- [ ] Split files 
- [x] Diff checkers
- [x] Remove duplicates and return a single file
- [x] Remove duplicates and return two file
- [x] highlight duplicates and return two file

**Comment by Temitayo40** [comment]
The link to the Document.
https://docs.google.com/document/d/1geaFUnZrwOcbsShBW3d561GXhLzWcI54WwcNxlIWluk/edit?usp=sharing

**Comment by knightwalkha** [comment]
Openpyxl would be used in sorting out the duplicates

**Comment by AlleyER16** [comment]
All features have been implemented except Split file and merge files. Those would be left for later updates
